DROP TABLE IF EXISTS groups;
CREATE TABLE IF NOT EXISTS groups (
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	group_title TEXT UNIQUE NOT NULL 
		
);

DROP TABLE IF EXISTS students;
CREATE TABLE IF NOT EXISTS students (
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	fullname TEXT UNIQUE NOT NULL,
	group_id INTEGER,
	FOREIGN KEY (group_id) REFERENCES groups (id)
		ON DELETE SET NULL
		ON UPDATE CASCADE
);

DROP TABLE IF EXISTS teachers;
CREATE TABLE IF NOT EXISTS teachers (
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	fullname TEXT UNIQUE NOT NULL
);

DROP TABLE IF EXISTS subjects;
CREATE TABLE IF NOT EXISTS subjects (
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	title TEXT UNIQUE NOT NULL,
	teacher_id INTEGER,
	FOREIGN KEY (teacher_id) REFERENCES teachers (id)
		ON DELETE SET NULL 
		ON UPDATE CASCADE
);

DROP TABLE IF EXISTS grades;
CREATE TABLE IF NOT EXISTS grades (
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	student_id INTEGER NOT NULL,
	subject_id INTEGER NOT NULL,
	grade INTEGER CHECK(grade >= 1 AND grade <= 100),
	grade_date DATE
	CHECK (
		grade_date IS NULL
		OR
		(date(grade_date) IS NOT NULL)
	),
	CHECK(
		(grade IS NOT NULL AND grade_date IS NOT NULL)
		OR
		(grade IS NULL AND grade_date IS NULL)
		),
	FOREIGN KEY (student_id) REFERENCES students (id)
		ON DELETE CASCADE
		ON UPDATE CASCADE
	,
	FOREIGN KEY (subject_id) REFERENCES subjects (id)
		ON DELETE CASCADE
		ON UPDATE CASCADE
);
