DROP TABLE IF EXISTS students;
CREATE TABLE IF NOT EXISTS students (
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	fullname TEXT UNIQUE NOT NULL,
	group_id INTEGER,
	FOREIGN KEY (group_id) REFERENCES groups (id)
		ON DELETE SET NULL
		ON UPDATE CASCADE
);