DROP TABLE IF EXISTS subjects;
CREATE TABLE IF NOT EXISTS subjects (
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	title TEXT UNIQUE NOT NULL,
	teacher_id INTEGER,
	FOREIGN KEY (teacher_id) REFERENCES teachers (id)
		ON DELETE SET NULL
		ON UPDATE CASCADE
);
